In [1]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
import sklearn.datasets as ds
import pandas as pd
from sklearn.model_selection import train_test_split

In [2]:
ds = ds.fetch_california_housing()

ds_features = pd.DataFrame(ds.data, columns=ds.feature_names)
ds_target = pd.DataFrame(ds.target, columns=ds.target_names)
ds_features.insert(0, 'Intercept', 1)

X_train, X_test = train_test_split(ds_features, test_size=0.2, shuffle=False)
y_train, y_test = train_test_split(ds_target, test_size=0.2, shuffle=False)

tX_train, ty_train = tf.convert_to_tensor(X_train, dtype=tf.float64), tf.convert_to_tensor(y_train, dtype=tf.float64) 
tX_test, ty_test = tf.convert_to_tensor(X_test, dtype=tf.float64), tf.convert_to_tensor(y_test, dtype=tf.float64) 

ds_features

2024-02-28 16:13:21.556780: I metal_plugin/src/device/metal_device.cc:1154] Metal device set to: Apple M1
2024-02-28 16:13:21.556822: I metal_plugin/src/device/metal_device.cc:296] systemMemory: 8.00 GB
2024-02-28 16:13:21.556838: I metal_plugin/src/device/metal_device.cc:313] maxCacheSize: 2.67 GB
2024-02-28 16:13:21.556918: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:306] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2024-02-28 16:13:21.556987: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:272] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)

,Intercept,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude
0,1,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23
1,1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22
2,1,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24
3,1,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25
4,1,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25
...,...,...,...,...,...,...,...,...,...
20635,1,1.5603,25.0,5.045455,1.133333,845.0,2.560606,39.48,-121.09
20636,1,2.5568,18.0,6.114035,1.315789,356.0,3.122807,39.49,-121.21
20637,1,1.7000,17.0,5.205543,1.120092,1007.0,2.325635,39.43,-121.22
20638,1,1.8672,18.0,5.329513,1.171920,741.0,2.123209,39.43,-121.32
20639,1,2.3886,16.0,5.254717,1.162264,1387.0,2.616981,39.37,-121.24

In [3]:
def ols(tp, xf):
    return tp[0] + tf.add_n([tf.multiply(tp[i],xf[i]) for i in range(1, len(tp))])

def mse(y_true, y_pred):
    return tf.reduce_mean(tf.square(y_true - y_pred))

In [5]:
X_transpose = tf.transpose(tX_train)
theta = tf.matmul(tf.linalg.inv(tf.matmul(X_transpose, tX_train)), tf.matmul(X_transpose, ty_train))
theta

<tf.Tensor: shape=(9, 1), dtype=float64, numpy=
array([[-3.63905103e+01],
       [ 4.47847084e-01],
       [ 9.40820722e-03],
       [-1.20960919e-01],
       [ 7.10267788e-01],
       [-1.47053238e-06],
       [-8.81496820e-03],
       [-4.21714509e-01],
       [-4.29775301e-01]])>